services:
  - type: web
    name: moticheck
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: your-db-name
          property: connectionString
    buildCommand: bundle install && bundle exec rails assets:precompile
    startCommand: bundle exec rails db:prepare && bundle exec rails server -b 0.0.0.0 -p $PORT

databases:
  - name: your-db-name
    databaseName: your_app_production
    user: your_app
