default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: password
  pool: 5

development:
  <<: *default
  database: moticheck_development

test:
  <<: *default
  database: moticheck_test
  username: postgres
  password: postgres
  host: localhost

production:
  <<: *default
  # Render が提供する DATABASE_URL を使用
  url: <%= ENV['DATABASE_URL'] %>

queue:
  <<: *production

cache:
  <<: *production
  database: <%= ENV['DB_CACHE_NAME'] || "#{ENV['DB_NAME']}_cache" %>

cable:
  <<: *default
  database: moticheck_production
