default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: password
  pool: 5

development:
  <<: *default
  database: moticheck_development
test:
  <<: *default
  database: moticheck_test
  username: postgres
  password: postgres
  host: localhost

production:
  <<: *default
  database: <%= ENV['DB_NAME'] %>
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>

cable:
  <<: *default
  database: moticheck_production
